int tmax(void);
int mul3(int x);
int getByte(int x,int y);
int roundUp(int x);
int swapOddandEven(int x);
int secondLowBit(int x);
int rotateNBits(int x, int n);
int fractions(int x);
int overflowCalc(int x, int y, int z);
unsigned float_abs(unsigned uf);
unsigned float_i2f(int x);
int oddParity(int x);
int bitNor(int x, int y);
int absVal(int x);
int isLessOrEqual(int x, int y);
int bitCount(int x);
int logicalShift(int x, int n);
unsigned float_half(unsigned uf);

int test_tconst(void);
int test_getByte(int x,int y);
int test_roundUp(int x);
int test_swapOddandEven(int x);
int test_secondLowBit(int x);
int test_rotateNBits(int x, int n);
int test_fractions(int x);
int test_hdOverflow(int x,int y);
int test_overflowCalc(int x, int y, int z);
unsigned test_float_abs(unsigned uf);
unsigned test_float_i2f(int x);
int test_oddParity(int x);
int test_bitNor(int x, int y);
int test_tmax(void);
int test_absVal(int x);
int test_isLessOrEqual(int x, int y);
int test_bitCount(int x);
int test_logicalShift(int x, int n);
unsigned test_float_half(unsigned uf);
int test_mul3(int x);
